export const indexTileToArrow = [
  'Arrow',
  'SourceBlock',
  'Blocker',
  'DelayArrow',
  'SignalDetector',
  'OppositeArrow',
  'OrthogonalArrow',
  'TrioArrow',
  'PulseGenerator',
  'ThroughArrow',
  'DiagonalArrow',
  'DoubleArrow',
  'ThroughNear',
  'ForwardDiagArrow',
  'NotGate',
  'AndGate',
  'XorGate',];
export const arrowToIndexTile = {
  Arrow: 0,
  SourceBlock: 1,
  Blocker: 2,
  DelayArrow: 3,
  SignalDetector: 4,
  OppositeArrow: 5,
  OrthogonalArrow: 6,
  TrioArrow: 7,
  PulseGenerator: 8,
  ThroughArrow: 9,
  DiagonalArrow: 10,
  DoubleArrow: 11,
  ThroughNear: 12,
  ForwardDiagArrow: 13,
  NotGate: 14,
  AndGate: 15,
  XorGate: 16,
};